# Generated by Django 5.0.6 on 2024-05-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('full_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('image_urls', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('bedrooms', models.FloatField()),
                ('baths', models.FloatField()),
                ('size', models.CharField(max_length=100)),
                ('HeatIncluded', models.BooleanField(default=False)),
                ('HotWaterIncluded', models.BooleanField(default=False)),
                ('CatAllowed', models.BooleanField(default=False)),
                ('DogAllowed', models.BooleanField(default=False)),
                ('Balcony', models.BooleanField(default=False)),
                ('InBuildingLaundry', models.BooleanField(default=False)),
                ('ParkingAvailable', models.BooleanField(default=False)),
                ('GymAvailable', models.BooleanField(default=False)),
            ],
        ),
    ]
