# Generated by Django 5.0.6 on 2024-05-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentscraper', '0002_alter_rentallisting_bedrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempletonListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.CharField(max_length=50)),
                ('baths', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('HeatIncluded', models.BooleanField()),
                ('HotWaterIncluded', models.BooleanField()),
                ('HydroIncluded', models.BooleanField()),
                ('ParkingAvailable', models.BooleanField()),
                ('CatAllowed', models.BooleanField()),
                ('DogAllowed', models.BooleanField()),
                ('GymAvailable', models.BooleanField()),
                ('InBuildingLaundry', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('full_url', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('price_per_sqft', models.CharField(max_length=50)),
                ('image_urls', models.TextField()),
            ],
        ),
    ]
