# Generated by Django 5.0.6 on 2024-05-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentscraper', '0005_rentallisting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('builder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('number_of_floors', models.IntegerField()),
                ('property_type', models.CharField(max_length=100)),
                ('number_of_units', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('air_conditioning', models.BooleanField(default=False)),
                ('balcony_patio', models.BooleanField(default=False)),
                ('convenience_store', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('fitness_center', models.BooleanField(default=False)),
                ('free_outdoor_parking', models.BooleanField(default=False)),
                ('heat_included', models.BooleanField(default=False)),
                ('laundry_facilities', models.BooleanField(default=False)),
                ('water_included', models.BooleanField(default=False)),
                ('parking_available', models.BooleanField(default=False)),
                ('parking_cost', models.IntegerField(blank=True, null=True)),
                ('parking_type', models.CharField(blank=True, max_length=100, null=True)),
                ('walk_score', models.IntegerField(blank=True, null=True)),
                ('transit_score', models.IntegerField(blank=True, null=True)),
                ('bike_score', models.IntegerField(blank=True, null=True)),
                ('nearest_police_station', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_superstore', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_pharmacy', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_hospital', models.CharField(blank=True, max_length=255, null=True)),
                ('time_to_nearest_hospital', models.CharField(blank=True, max_length=50, null=True)),
                ('time_to_nearest_police_station', models.CharField(blank=True, max_length=50, null=True)),
                ('time_to_nearest_superstore', models.CharField(blank=True, max_length=50, null=True)),
                ('time_to_nearest_pharmacy', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
