# Generated by Django 5.0.6 on 2024-05-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentscraper', '0006_buildingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
