# Generated by Django 5.0.6 on 2024-05-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentscraper', '0007_buildingdetails_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='WestwoodListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('price', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('den_included', models.BooleanField(default=False)),
                ('parking_available', models.BooleanField(default=False)),
                ('parking', models.CharField(blank=True, max_length=100, null=True)),
                ('gym_available', models.BooleanField(default=False)),
                ('heat_included', models.BooleanField(default=False)),
                ('hot_water_included', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('title', models.CharField(max_length=255)),
                ('full_url', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=100)),
            ],
        ),
    ]
