# Generated by Django 5.0.6 on 2024-05-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentscraper', '0008_westwoodlistings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='westwoodlistings',
            name='baths',
            field=models.FloatField(),
        ),
    ]
