# Generated by Django 5.0.6 on 2024-05-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentscraper', '0009_alter_westwoodlistings_baths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='westwoodlistings',
            name='bedrooms',
            field=models.CharField(max_length=50),
        ),
    ]
