# Generated by Django 5.0.6 on 2024-05-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentscraper', '0011_futureproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureproperties',
            name='builder',
            field=models.CharField(max_length=2500),
        ),
    ]
