# Generated by Django 5.0.6 on 2024-05-17 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentscraper', '0012_alter_futureproperties_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='westwoodlistings',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
